steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "$$GOOGLE_APPLICATION_CREDENTIALS_CONTENT" > /tmp/service-account-key.json
        export GOOGLE_APPLICATION_CREDENTIALS="/tmp/service-account-key.json"
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/learn-language-flask-app", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/learn-language-flask-app"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "beta"
      - "run"
      - "deploy"
      - "learn-language-flask-app"
      - "--image"
      - "gcr.io/$PROJECT_ID/learn-language-flask-app"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"

secrets:
  - secretEnv: ["GOOGLE_APPLICATION_CREDENTIALS_CONTENT"]

availableSecrets:
  secretManager:
    - versionName: "projects/776682186119/secrets/service-account-key/versions/latest"
      env: "GOOGLE_APPLICATION_CREDENTIALS_CONTENT"
