steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/learn-language-flask-app", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/learn-language-flask-app"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "learn-language-flask-app",
        "--image",
        "gcr.io/$PROJECT_ID/learn-language-flask-app",
        "--region",
        "us-central1",
        "--platform",
        "managed",
      ]
